import { Camera, BookOpen, ChefHat, Search } from "lucide-react";

export const SITE_STATS = [
  { label: "Free Scans", val: "10/mo" },
  { label: "Recipes Generated", val: "1M+" },
  { label: "Cost to Start", val: "$0" },
  { label: "App Store Rating", val: "4.9" },
];

export const FEATURES = [
  {
    title: "Scan Your Pantry",
    description:
      "Photo recognition that actually works. Know what you have instantly.",
    icon: Camera,
    limit: "10 scans/mo free",
  },
  {
    title: "AI Chef Suggestions",
    description:
      "Turn random ingredients into a gourmet meal. Zero food waste.",
    icon: ChefHat,
    limit: "5 meals/mo free",
  },
  {
    title: "Search Any Dish",
    description:
      "Find any recipe instantly. Filter by cuisine, time, or dietary needs.",
    icon: Search,
    limit: "Unlimited searches",
  },
  {
    title: "Digital Cookbook",
    description: "Save your favorites. Export as PDF. Share with family.",
    icon: BookOpen,
    limit: "3 saves/mo free",
  },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: "01",
    title: "Scan",
    desc: "Point camera at fridge. AI identifies ingredients.",
  },
  {
    step: "02",
    title: "Select",
    desc: "Choose a generated recipe based on your mood.",
  },
  {
    step: "03",
    title: "Savor",
    desc: "Follow simple steps. Eat delicious food.",
  },
];

// Helper function for category emojis
export function getCategoryEmoji(category) {
  const emojiMap = {
    Beef: "🥩",
    Chicken: "🍗",
    Dessert: "🍰",
    Lamb: "🍖",
    Miscellaneous: "🍴",
    Pasta: "🍝",
    Pork: "🥓",
    Seafood: "🦐",
    Side: "🥗",
    Starter: "🥟",
    Vegan: "🥬",
    Vegetarian: "🥕",
    Breakfast: "🍳",
    Goat: "🐐",
  };
  return emojiMap[category] || "🍽️";
}

// Helper function for country flags
export function getCountryFlag(country) {
  const emojiMap = {
    American: "🗽",
    Afghan: "🏔️",
    Albanian: "🦅",
    Algerian: "🏜️",
    Andorran: "⛰️",
    Angolan: "🌍",
    Antiguan: "🏖️",
    Argentinian: "⚽",
    Armenian: "🍇",
    Australian: "🦘",
    Austrian: "🎼",
    Azerbaijani: "🔥",
    Bahamian: "🏝️",
    Bahraini: "🏜️",
    Bangladeshi: "🌿",
    Barbadian: "🌊",
    Belarusian: "🌾",
    Belgian: "🍫",
    Belizean: "🌴",
    Beninese: "🌍",
    Bhutanese: "🐉",
    Bolivian: "🏔️",
    Bosnian: "🏔️",
    Botswanan: "🦁",
    Brazilian: "🌴",
    Bruneian: "🛕",
    Bulgarian: "🌹",
    Burkinabe: "🌍",
    Burundian: "🌍",
    Cambodian: "🛕",
    Cameroonian: "🦁",
    Canadian: "🍁",
    Cape_Verdean: "🌊",
    Central_African: "🌍",
    Chadian: "🏜️",
    Chilean: "🏔️",
    Chinese: "🐉",
    Colombian: "☕",
    Comorian: "🌺",
    Congolese: "🌍",
    Costa_Rican: "🌿",
    Croatian: "⚽",
    Cuban: "🎵",
    Cypriot: "🏛️",
    Czech: "🍺",
    Danish: "🧜",
    Djiboutian: "🏜️",
    Dutch: "🌷",
    East_Timorese: "🌴",
    Ecuadorian: "🌿",
    Egyptian: "🐫",
    Emirati: "🏙️",
    Equatorial_Guinean: "🌍",
    Eritrean: "🌍",
    Estonian: "🌲",
    Eswatini: "🌍",
    Ethiopian: "☕",
    Fijian: "🌊",
    Filipino: "🌴",
    Finnish: "🧖",
    French: "🥐",
    Gabonese: "🌳",
    Gambian: "🌍",
    Georgian: "🍷",
    German: "🍻",
    Ghanaian: "🥁",
    Greek: "🏛️",
    Grenadian: "🌶️",
    Guatemalan: "🦜",
    Guinean: "🌍",
    Guinea_Bissauan: "🌍",
    Guyanese: "🌿",
    Haitian: "🌺",
    Honduran: "🌴",
    Hungarian: "🫑",
    Icelandic: "🌋",
    Indian: "🪷",
    Indonesian: "🌋",
    Iranian: "🏺",
    Iraqi: "🏛️",
    Irish: "☘️",
    Israeli: "✡️",
    Italian: "🍕",
    Ivorian: "🌍",
    Jamaican: "🌴",
    Japanese: "🗾",
    Jordanian: "🏜️",
    Kazakhstani: "🦅",
    Kenyan: "🦒",
    Kiribati: "🌊",
    Korean: "🌸",
    Kuwaiti: "🛢️",
    Kyrgyz: "🏔️",
    Laotian: "🐘",
    Latvian: "🌲",
    Lebanese: "🌲",
    Lesothan: "🏔️",
    Liberian: "🌍",
    Libyan: "🏜️",
    Liechtensteiner: "🏰",
    Lithuanian: "🌾",
    Luxembourgish: "🏰",
    Malagasy: "🦎",
    Malawian: "🌍",
    Malaysian: "🌺",
    Maldivian: "🌊",
    Malian: "🏜️",
    Maltese: "⚓",
    Marshallese: "🌊",
    Mauritanian: "🏜️",
    Mauritian: "🌺",
    Mexican: "🌮",
    Micronesian: "🌊",
    Moldovan: "🍇",
    Monacan: "🏎️",
    Mongolian: "🐎",
    Montenegrin: "🏔️",
    Moroccan: "🕌",
    Mozambican: "🌍",
    Namibian: "🦁",
    Nauruan: "🌊",
    Nepali: "🏔️",
    New_Zealander: "🥝",
    Nicaraguan: "🌋",
    Nigerian: "🦅",
    Nigerien: "🏜️",
    North_Korean: "⭐",
    North_Macedonian: "☀️",
    Norwegian: "❄️",
    Omani: "🏜️",
    Pakistani: "🌹",
    Palauan: "🌊",
    Palestinian: "🫒",
    Panamanian: "🚢",
    Papua_New_Guinean: "🦜",
    Paraguayan: "⭐",
    Peruvian: "🦙",
    Polish: "🦅",
    Portuguese: "🚢",
    Qatari: "🏙️",
    Romanian: "🏰",
    Russian: "❄️",
    Rwandan: "🌍",
    Saint_Kitts_and_Nevisian: "🌺",
    Saint_Lucian: "🌴",
    Saint_Vincentian: "🌴",
    Salvadoran: "🌋",
    Samoan: "🌊",
    San_Marinese: "⛰️",
    Sao_Tomean: "🌍",
    Saudi_Arabian: "🕋",
    Senegalese: "🌍",
    Serbian: "🏔️",
    Seychellois: "🌊",
    Sierra_Leonean: "🌍",
    Singaporean: "🦁",
    Slovakian: "🏔️",
    Slovenian: "🏔️",
    Solomon_Islander: "🌊",
    Somali: "🌍",
    South_African: "🦁",
    South_Korean: "🌸",
    South_Sudanese: "🌍",
    Spanish: "💃",
    Sri_Lankan: "🌿",
    Sudanese: "🏜️",
    Surinamese: "🌿",
    Swedish: "🎄",
    Swiss: "🧀",
    Syrian: "🏛️",
    Taiwanese: "🏮",
    Tajik: "🏔️",
    Tanzanian: "🦒",
    Thai: "🛕",
    Togolese: "🌍",
    Tongan: "🌊",
    Trinidadian: "🥁",
    Tunisian: "🏜️",
    Turkish: "🧿",
    Turkmen: "🏜️",
    Tuvaluan: "🌊",
    Ugandan: "🦍",
    Ukrainian: "🌻",
    Uruguayan: "⚽",
    Uzbek: "🌸",
    Vanuatuan: "🌋",
    Vatican: "✝️",
    Venezuelan: "🌞",
    Vietnamese: "🍜",
    Yemeni: "🏜️",
    Zambian: "🌍",
    Zimbabwean: "🦁",
  };

  return emojiMap[country] ?? "🌍";
}